resolver: nightly-2019-11-21

packages:
- lol/
- lol-cpp/
- lol-apps/
# - lol-repa/

extra-deps:
- DRBG-0.5.5
- monadcryptorandom-0.7.2.1
- protocol-buffers-2.4.13
- protocol-buffers-descriptor-2.4.13
- cipher-aes128-0.7.0.5
- repa-3.4.1.4
