# For more information, see: http://docs.haskellstack.org/en/stable/yaml_configuration.html
# vim: nospell

resolver: lts-5.14

# Local packages, usually specified by relative directory name
packages:
- lol
- lol-test
# - 'apps'
# - 'compiler'

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- arithmoi-0.4.1.3
- distributive-0.4.4
- non-negative-0.1.1
- numeric-prelude-0.4.2
- semigroupoids-4.3
- storable-record-0.0.3.1
- tagged-transformer-0.8

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 1.0.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]

# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
