# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RLWE.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Lol_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='RLWE.proto',
  package='',
  serialized_pb=_b('\n\nRLWE.proto\x1a\tLol.proto\"/\n\x0bSampleCont1\x12\x0f\n\x01\x61\x18\x01 \x02(\x0b\x32\x04.Rq1\x12\x0f\n\x01\x62\x18\x02 \x02(\x0b\x32\x04.Kq1\"/\n\x0bSampleDisc1\x12\x0f\n\x01\x61\x18\x01 \x02(\x0b\x32\x04.Rq1\x12\x0f\n\x01\x62\x18\x02 \x02(\x0b\x32\x04.Rq1\"/\n\x0bSampleRLWR1\x12\x0f\n\x01\x61\x18\x01 \x02(\x0b\x32\x04.Rq1\x12\x0f\n\x01\x62\x18\x02 \x02(\x0b\x32\x04.Rq1\":\n\nSampleCont\x12\x15\n\x01\x61\x18\x01 \x02(\x0b\x32\n.RqProduct\x12\x15\n\x01\x62\x18\x02 \x02(\x0b\x32\n.KqProduct\":\n\nSampleDisc\x12\x15\n\x01\x61\x18\x01 \x02(\x0b\x32\n.RqProduct\x12\x15\n\x01\x62\x18\x02 \x02(\x0b\x32\n.RqProduct\":\n\nSampleRLWR\x12\x15\n\x01\x61\x18\x01 \x02(\x0b\x32\n.RqProduct\x12\x15\n\x01\x62\x18\x02 \x02(\x0b\x32\n.RqProduct')
  ,
  dependencies=[Lol_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SAMPLECONT1 = _descriptor.Descriptor(
  name='SampleCont1',
  full_name='SampleCont1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='SampleCont1.a', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='b', full_name='SampleCont1.b', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=72,
)


_SAMPLEDISC1 = _descriptor.Descriptor(
  name='SampleDisc1',
  full_name='SampleDisc1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='SampleDisc1.a', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='b', full_name='SampleDisc1.b', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=121,
)


_SAMPLERLWR1 = _descriptor.Descriptor(
  name='SampleRLWR1',
  full_name='SampleRLWR1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='SampleRLWR1.a', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='b', full_name='SampleRLWR1.b', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=170,
)


_SAMPLECONT = _descriptor.Descriptor(
  name='SampleCont',
  full_name='SampleCont',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='SampleCont.a', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='b', full_name='SampleCont.b', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=230,
)


_SAMPLEDISC = _descriptor.Descriptor(
  name='SampleDisc',
  full_name='SampleDisc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='SampleDisc.a', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='b', full_name='SampleDisc.b', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=290,
)


_SAMPLERLWR = _descriptor.Descriptor(
  name='SampleRLWR',
  full_name='SampleRLWR',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='SampleRLWR.a', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='b', full_name='SampleRLWR.b', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=292,
  serialized_end=350,
)

_SAMPLECONT1.fields_by_name['a'].message_type = Lol_pb2._RQ1
_SAMPLECONT1.fields_by_name['b'].message_type = Lol_pb2._KQ1
_SAMPLEDISC1.fields_by_name['a'].message_type = Lol_pb2._RQ1
_SAMPLEDISC1.fields_by_name['b'].message_type = Lol_pb2._RQ1
_SAMPLERLWR1.fields_by_name['a'].message_type = Lol_pb2._RQ1
_SAMPLERLWR1.fields_by_name['b'].message_type = Lol_pb2._RQ1
_SAMPLECONT.fields_by_name['a'].message_type = Lol_pb2._RQPRODUCT
_SAMPLECONT.fields_by_name['b'].message_type = Lol_pb2._KQPRODUCT
_SAMPLEDISC.fields_by_name['a'].message_type = Lol_pb2._RQPRODUCT
_SAMPLEDISC.fields_by_name['b'].message_type = Lol_pb2._RQPRODUCT
_SAMPLERLWR.fields_by_name['a'].message_type = Lol_pb2._RQPRODUCT
_SAMPLERLWR.fields_by_name['b'].message_type = Lol_pb2._RQPRODUCT
DESCRIPTOR.message_types_by_name['SampleCont1'] = _SAMPLECONT1
DESCRIPTOR.message_types_by_name['SampleDisc1'] = _SAMPLEDISC1
DESCRIPTOR.message_types_by_name['SampleRLWR1'] = _SAMPLERLWR1
DESCRIPTOR.message_types_by_name['SampleCont'] = _SAMPLECONT
DESCRIPTOR.message_types_by_name['SampleDisc'] = _SAMPLEDISC
DESCRIPTOR.message_types_by_name['SampleRLWR'] = _SAMPLERLWR

SampleCont1 = _reflection.GeneratedProtocolMessageType('SampleCont1', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLECONT1,
  __module__ = 'RLWE_pb2'
  # @@protoc_insertion_point(class_scope:SampleCont1)
  ))
_sym_db.RegisterMessage(SampleCont1)

SampleDisc1 = _reflection.GeneratedProtocolMessageType('SampleDisc1', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLEDISC1,
  __module__ = 'RLWE_pb2'
  # @@protoc_insertion_point(class_scope:SampleDisc1)
  ))
_sym_db.RegisterMessage(SampleDisc1)

SampleRLWR1 = _reflection.GeneratedProtocolMessageType('SampleRLWR1', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLERLWR1,
  __module__ = 'RLWE_pb2'
  # @@protoc_insertion_point(class_scope:SampleRLWR1)
  ))
_sym_db.RegisterMessage(SampleRLWR1)

SampleCont = _reflection.GeneratedProtocolMessageType('SampleCont', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLECONT,
  __module__ = 'RLWE_pb2'
  # @@protoc_insertion_point(class_scope:SampleCont)
  ))
_sym_db.RegisterMessage(SampleCont)

SampleDisc = _reflection.GeneratedProtocolMessageType('SampleDisc', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLEDISC,
  __module__ = 'RLWE_pb2'
  # @@protoc_insertion_point(class_scope:SampleDisc)
  ))
_sym_db.RegisterMessage(SampleDisc)

SampleRLWR = _reflection.GeneratedProtocolMessageType('SampleRLWR', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLERLWR,
  __module__ = 'RLWE_pb2'
  # @@protoc_insertion_point(class_scope:SampleRLWR)
  ))
_sym_db.RegisterMessage(SampleRLWR)


# @@protoc_insertion_point(module_scope)
