{-# LANGUAGE DataKinds, ScopedTypeVariables, TemplateHaskell, TypeFamilies #-}

--Don't modify this file: it is generated by `mkReader` in Challenges.MakeReader

module Challenges.Reader where

import Challenges.MakeReader
import Challenges.ProtoReader
import Control.Applicative
import Control.Monad.Trans.Maybe
import Crypto.Lol (fType,Proxy(..))
import Data.Maybe
import Utils

readChallenges secretDir (_::Proxy t) = catMaybes <$> (mapM runMaybeT [
  tryReadLWEChallenge secretDir "lwe-32-257-1.0" (Proxy::Proxy (LWEChallenge Double t $(fType 32) (Zq 257))),
  tryReadLWEChallenge secretDir "lwe-32-257-2.0" (Proxy::Proxy (LWEChallenge Double t $(fType 32) (Zq 257)))])