{-# LANGUAGE DataKinds, ScopedTypeVariables, TemplateHaskell, TypeFamilies #-}

--Don't modify this file: it is generated by `mkReader` in Challenges.MakeReader

module Challenges.Reader where

import Challenges.LWE
import Challenges.MakeReader
import Control.Applicative
import Control.Monad.Trans.Maybe
import Crypto.Lol (fType,Proxy)
import Data.Maybe
import Utils

readChallenges (_::Proxy t) = catMaybes <$> (sequence $ map runMaybeT [
  Challenge "lwe-8-129-1.0" <$> (tryReadChallenge "lwe-8-129-1.0" :: MaybeT IO (LWEChallenge Double t $(fType 8) (Zq 129))),
  Challenge "lwe-8-129-2.0" <$> (tryReadChallenge "lwe-8-129-2.0" :: MaybeT IO (LWEChallenge Double t $(fType 8) (Zq 129)))])