#!/usr/bin/env bash

package="$1"
cabal_file="$package/$package.cabal"

if [[ -z "$package" ]]; then
  echo "usage: $0 package" >&2
  exit 1
fi

hpack "$package"

if ! git diff --quiet HEAD "$cabal_file"; then
  echo "regenerating $cabal_file resulted in a change, please apply the following patch:" >&2
  git diff --patch --no-color HEAD "$cabal_file"
  exit 1
fi
